In [1]:
from pathlib import Path

In [2]:
def check_path_depth(fp, parent):
    print(fp)
    print(parent)
    depth = 0
    while fp.parent != parent:
        depth += 1
        fp = fp.parent
        print(fp)
    return depth

In [4]:
# fp = Path('/home/rdcrlzh1s1/miniforge3/LICENSE.txt')
# parent= Path('/home/rdcrlzh1s/')
# check_path_depth(fp, parent)

In [38]:
import pandas as pd
df = pd.read_csv('/data/wcp/20240724/am/nav/ATLANS-20240724-104012_OutC_POSTPROCESSING-replay.xpf.old', comment = '#', index_col= 0)

In [52]:
df.index.duplicated().sum()

766

In [47]:
df = pd.read_csv('/data/wcp/20240724/am/nav/old/ATLANS-20240724-104012_OutC_POSTPROCESSING-replay.xpf.old', comment = '#', index_col= 0, names = ['time', 'latitude','longitude','altitude','roll','pitch','heading'])
df

            latitude  longitude     altitude      roll     pitch   heading
time
311909.220  0.772426  -1.995138  1643.812866  0.011173  0.002104  2.726329
311909.220  0.772426  -1.995138  1643.812866  0.011173  0.002104  2.726329
311909.225  0.772426  -1.995138  1643.812866  0.011167  0.002103  2.726330
311909.225  0.772426  -1.995138  1643.812866  0.011167  0.002103  2.726330
311909.230  0.772426  -1.995138  1643.812866  0.011162  0.002103  2.726328
...              ...        ...          ...       ...       ...       ...
315620.235  0.772329  -1.995113  1652.472900  0.000375  0.000398  5.900559
315620.240  0.772329  -1.995113  1652.472900  0.000376  0.000396  5.900558
315620.245  0.772329  -1.995113  1652.472900  0.000376  0.000395  5.900557
315620.250  0.772329  -1.995113  1652.472900  0.000374  0.000396  5.900556
315620.255  0.772329  -1.995113  1652.472900  0.000373  0.000396  5.900556

[742974 rows x 6 columns]

In [59]:
p = Path('/data/wcp/20240724/am/nav/old/ATLANS-20240724-104012_OutC_POSTPROCESSING-replay.xpf.old')
p.with_suffix(f'.clean{p.suffix}')

PosixPath('/data/wcp/20240724/am/nav/old/ATLANS-20240724-104012_OutC_POSTPROCESSING-replay.xpf.clean.old')

In [49]:
df.drop_duplicates().to_csv('/data/wcp/20240724/am/nav/old/test.txt', header = False)

In [42]:
df.drop_duplicates().iloc[1:].to_csv('/data/wcp/20240724/am/nav/ATLANS-20240724-104012_OutC_POSTPROCESSING-replay.xpf.txt')

In [41]:
df.drop_duplicates().iloc[1:]

,0.772426136525,-1.995137567705,1643.812866210938,0.011172907443,0.002103981135,2.726329140607
311909.2200001,,,,,,
311909.225,0.772426,-1.995138,1643.812866,0.011167,0.002103,2.726330
311909.230,0.772426,-1.995138,1643.812866,0.011162,0.002103,2.726328
311909.235,0.772426,-1.995138,1643.812866,0.011158,0.002102,2.726329
311909.240,0.772426,-1.995138,1643.812866,0.011155,0.002102,2.726328
311909.245,0.772426,-1.995138,1643.812866,0.011154,0.002102,2.726329
...,...,...,...,...,...,...
315620.235,0.772329,-1.995113,1652.472900,0.000375,0.000398,5.900559
315620.240,0.772329,-1.995113,1652.472900,0.000376,0.000396,5.900558
315620.245,0.772329,-1.995113,1652.472900,0.000376,0.000395,5.900557
315620.250,0.772329,-1.995113,1652.472900,0.000374,0.000396,5.900556
315620.255,0.772329,-1.995113,1652.472900,0.000373,0.000396,5.900556

In [29]:
df.index.drop_duplicates()

Index([311909.2200001, 311909.2250001, 311909.2300001, 311909.2350001,
       311909.2400001, 311909.2450001, 311909.2500001, 311909.2550001,
       311909.2600001, 311909.2650001,
       ...
       315620.2100001, 315620.2150001, 315620.2200001, 315620.2250001,
       315620.2300001, 315620.2350001, 315620.2400001, 315620.2450001,
       315620.2500001, 315620.2550001],
      dtype='float64', name='time', length=742208)